apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy: {}
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.35.1
        name: audiobookshelf
        ports:
        - containerPort: 3005

        securityContext:
          allowPrivilegeEscalation: false          

        envFrom:
          - configMapRef:
              name: audiobookshelf-configmap

        volumeMounts:
          - name: audiobookshelf-data
            mountPath: /config
            subPath: config
         
          - name: audiobookshelf-data
            mountPath: /metadata
            subPath: metadata

          - name: audiobookshelf-library
            mountPath: /audiobooks
            subPath: audiobooks

          - name: audiobookshelf-library
            mountPath: /podcasts
            subPath: podcasts

      restartPolicy: Always

      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc

        - name: audiobookshelf-library
          persistentVolumeClaim:
            claimName: audiobookshelf-library-pvc
