apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:R4Ji3w==,iv:IbkreiF/d1fQIGBbSql8FelawOJ4Yi/OpMh6KLsXzjs=,tag:ZjiMV0tUzFaGC2YY/tEaZA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:oGxkKj5DhUUXTcKR,iv:zmTtapvrTnAToBgedQQ6QGIb4sYyzaBsglTn+3ARI7U=,tag:NfZeu34INO3DfRSH4wRZAA==,type:str]
kind: Secret
metadata:
    name: linkding-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZEZRSHZjS21XSGRyQ3cw
            MFArekVNRUdrdU1ZZlNwRlhsSktVRER6M3hzCi84bGx1OEdPM1FuZ1Y5S2VsOXkv
            L3FQS21lWjZhaXA3SS9kb3J3bVl0SDQKLS0tIDk2L0RRRHJpTXpCZ0FpbFN3c3Vl
            eXMvalNvcmVJZXkvQ2RKaGZrTnhMc28KOg1KB1zvMG0FnXGcd80bqp+0NefM/wJe
            hV3VmzfX7v8yy40aOWlc8PVK90ZRbEg0ustUlRLkdUv3TL+u1eHfbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mh4wjetrkaxd4e5us0vn8vcw75rpqpx54zwtfar3s0767j3f4qdsayuesz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T18:33:38Z"
    mac: ENC[AES256_GCM,data:nq/fk3Vbg07pSEQFxdOUvgkpeIRrLfjql8EufxAkEMa6//Lc9T7hxf1uM/TOpG7r7FBLlvMYzBtWxQ/CVDYO5bDj37QVjaBpvsdyVFpXkfoIgeNOmC3oMgY4XrME3UF1/e9cLVSIKv6iMH6gEOfjbFs9Qkot05PzGLDNpZRbn1o=,iv:qD0bMqvEw1fva97Yy9X92tzVjS/E5VVW4pdSW0BXCVI=,tag:bFJYHla3Xcv6LEGSm4cr8Q==,type:str]
    version: 3.13.1
