apiVersion: v1
data:
    password: ENC[AES256_GCM,data:qTEeTtBx5rNk,iv:K/X8oyzi9iz59s0k+bG+OtYkBym3125ZtBO8fHe+jIE=,tag:0BM3fBzJeB9ohC+3+fCk4g==,type:str]
    user: ENC[AES256_GCM,data:fwQ=,iv:3KOOb7zs5TeoweXT28/iTM4W3VNJE/HEZEJl1crce1Q=,tag:/iFVeYxjozVZuB8ofpdqwg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeEhLZEFsSVlDZTRxVnRy
            eDZKOGt0ZjVqU1h2VVlER2h4M2lnaVJwVVNjCnVBb05XVlZkZGtQbEdGeGNaUjFz
            WEVkb085eXJ4QzVJdHNrMDlUR24rR3MKLS0tIGkxTU1qdUx6RG1aTTk4L1R0M0F0
            ZlRKMU9zVElpMGRHRkpsN3pMUzA2bGsKB2EcdFQ2jWSKr94Ht7xRdTmmsCZ3ld0w
            1oM2RY3MRa0YIjn/g2YFvlXOUEApAlUhOf2Kl8q0+eFLe3O3RLg+Yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mh4wjetrkaxd4e5us0vn8vcw75rpqpx54zwtfar3s0767j3f4qdsayuesz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T19:01:57Z"
    mac: ENC[AES256_GCM,data:18fhbhRj2EhglKrC45mS6IYpJnsepC/wIhe8EWcTtbmMLk6FvhJcMiboU2xGsYLqOVYhEAE884iAjIJpXEtK2A5hdqPmQg1q2yNRST8pOHM+4Bo+Zp+RkbvGYuGpJB1MTxUkU29K1GoquoJb5RLeK/FGz3b9Azp2e7Xg4AjkkOA=,iv:3Nsu2iEkKUwxHO/qkr6UNrC/JkKao6bqgr/fwQN+ens=,tag:eUT0FvrO6z4aWseeHQQwgA==,type:str]
    version: 3.13.1
