apiVersion: v1
data:
    password: ENC[AES256_GCM,data:JVrzxLlQRB0=,iv:gEACXJk3zFwNfi9u4CLCFwYQPmt+onHZY8pkG0gebJA=,tag:sLDrESQrFH7wuwSkm6A45w==,type:str]
    user: ENC[AES256_GCM,data:djpbHV0SQbo=,iv:rLqIes6uLtOZyEe2H49/WcdSKlu0D24Q9OPZU9DYmtE=,tag:vbXysGdshe5cNIcRLxLt1g==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd3NNTlBUcXIvejdNNGs3
            T0tCSWJrd1lCR0c1L0NyZGlIUUxPb1dwaEdrCjQrTDgvSUU0MHRSM0ZtRHFDS3BU
            Yjl6Y1BpYUZzT2N2VnlyU2d6WHZoWDAKLS0tIG0xa2dKd3dtV3JrdDMzb3E4cWNN
            Nk5TMWtqQ21sYkdqeEFrVGpULzRsaEkKsdLmjbfeLFZaGBU7LEvqHCmbttPU79eT
            gQGYUibshGs5pvoyR733oskA8nU7EOXGdZQCI6MxVkQS/WUQfpF6Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mh4wjetrkaxd4e5us0vn8vcw75rpqpx54zwtfar3s0767j3f4qdsayuesz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T19:54:39Z"
    mac: ENC[AES256_GCM,data:syjikptFvOvw4TLs+yL5ZTUYWHxmafqjybZ435agjgPWlK1pTBzyAO3uoxF8+KkzyR6/oxvbF7Pf2Z7c8QaB2RbYvMjKjO7puIOUb4Xo5swkIav+DjJdRczDgxm44XJNf5nz5rEeidAnvSd8UWz4mvFWym1+CD7vYz19TPdS79Q=,iv:/vb9YvBfIEOVoAuJi/yMRT+cIRY8ja7cC/pBKqefsW0=,tag:44MWLxN0hy6TO1O6TBTVTQ==,type:str]
    version: 3.13.1
