apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:wZyPyjtpZ3MDckuBvds5gHoFTlyekoQoWQKH208eV9YfJTS7OJAo7pOr9GXg64by/PDE2l46e1O854bvfOaUMLd5g/NQHafyVWG8wd6SRsmmIahZ1ddXUudvStXirrqkBXUFDu1Welb6xdI06NJ8r6bMeetR18pkkLRDn3wRKS9SqmptzAgdy1xq8py4z5/P0aTpLDDBzJs3pcupjmy1XlZkKcn+zgzcImOhgR1G0JRLY9IA6X+Ahp81k64Vx/95sXq5Uj/BYuTX0yViEK2APDNmhoBSbtxLkRjgCNWQZrr2v2IYLv3wKCPkdAo=,iv:E7vrlWoqN0x+6ieNPz5e6/pai59PWNzAHi0Ebx7X2sA=,tag:8wlOM20g39qXv3h5QPAd7w==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMUprU1hXT1JkRXg4aXJF
            TU9Tek12V0syVU9yWEtibldOWk5yY1JhL2xVCjBvZXNxOXd2K0sxVGwvSTUwbFVM
            ZHFjbkVOUWRVbGtKRys2NWJ0QlFTWVUKLS0tIEdodmtMTHZGUmhSdi83K3BEY1dY
            MFc4TGpndFBvQW1VaXFKMHB0Nk16aDQKbCLnoEDjnExoKd80O6Fu7Fuq0Ofw2TjT
            AK7I+pRNDjb0tZ9ZqzvRf60djyYqtPtFKo3U91x/E0HKBVetRdITVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mh4wjetrkaxd4e5us0vn8vcw75rpqpx54zwtfar3s0767j3f4qdsayuesz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T19:37:58Z"
    mac: ENC[AES256_GCM,data:sKyl8TvZKdDhSIynCG/GizlRs6n85oFu5vr/rQdcB3L8O6Ed1OW3rR9onVXxTt3lrtGudd+0B6DiRS+LWjKN7xVRiLSGUSNzN978YT2jFWn4+NMqEMa56F0kT8uIOuVOZ4JGSqUxfA5JT+Y29eKhbbb7/7sE+LVBqwTxGq6KNbw=,iv:BnJz9u1BIL39/dDMQGQkRfEg6iTA9mRjsz3HHqROYmg=,tag:z2eCL4yVuOq5OQShykEq0w==,type:str]
    version: 3.13.1
